// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/Chat.vue')['default']
    ChatEvent: typeof import('./src/components/ChatEvent.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
  }
}

export { }
