// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/Chat.vue')['default']
    ChatEvent: typeof import('./src/components/ChatEvent.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NTime: typeof import('naive-ui')['NTime']
  }
}

export { }
